config/routes.rb
TaskManager::Application.routes.draw do

  root to: 'sessions#home'

  resources :projects, except: [:show] do
    resources :tasks, except: [:index, :new] do
      member do
        put 'change_priority'
      end
    end
  end

  match '/projects' => 'projects#index', via: [:delete, :put, :get]

  resources :sessions, except: [:show, :edit, :update]
  match '/logout' => 'sessions#destroy', via: :delete
  match '/login' => 'sessions#new'

  resources :users, only: [:create]

  match '*a' => 'application#rescue404'

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  description :string(255)
#  user_id     :integer
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

class Project < ActiveRecord::Base
  belongs_to :user
  attr_accessible :description, :name
  has_many :task, :dependent => :destroy, :order => "priority ASC"

  scope :with_task, includes(:task)

  validates :name, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 255 }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :loged_in
  before_filter :get_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = current_user.project.with_task.all
    @task = Task.new
    respond_to do |format|
      format.html { render partial: 'projects', collection: @projects, as: :project }
    end
  end

  def new
    @project = Project.new
    render partial: 'project'
  end

  def edit
    render partial: 'project'
  end

  def create
    @project = current_user.project.build(params[:project])
    respond_to do |format|
      if @project.save
          format.json { head :no_content }
        else
          format.json { render json: @project.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update_attributes(params[:project])
          format.json { head :no_content }
        else
          format.json { render json: @project.errors.full_messages, status: :unprocessable_entity }
      end    
    end    
  end

  def destroy
    respond_to do |format|
      if @project.destroy
          format.json { head :no_content }
        else
          format.json { render json: @project.errors.full_messages, status: :unprocessable_entity }
      end    
    end
  end  

  private

  def get_project
    @project = current_user.project.find_by_id(params[:id])
    
    if @project.nil?
      render json: ["Can't get such project"], status: :unprocessable_entity
    end
  end

end

app/views/projects/_project.html.erb
<div class="modal" id="myModal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3><%= controller.action_name.capitalize %> Project</h3>
  </div>

<%= simple_form_for(@project, remote: true, :html => { :class => "form-horizontal project-add-edit"}) do |f| %>
  <div class="modal-body">
    <div id="alert-area-modal"></div>

    <%= f.input :name %>
  </div>
  <div class="modal-footer">
    <%= link_to "Cancel", '#', :class=>"btn", :"data-dismiss" => "modal" %>
    <%= f.submit "Save",:class=>"btn btn-primary" %>
  </div>

<% end %>

</div>

app/views/projects/_projects.html.erb
<table class="table table-striped table-bordered table-condensed projects-list" id="<%= dom_id(project) %>">

  <!-- Project row -->
  <tr>
    <th colspan="2" class="name"><p><%= project.name %></p></th>
    <th class="control">
      <ul class="nav nav-pills">
        <li>
          <%= link_to [:edit, project], class: "project-edit", remote: true do %>
            <i class="icon-pencil"></i>
          <% end %>
        </li>
        <li>
          <%= link_to project, class: "project-delete", method: :delete, data: { confirm: 'Are you sure?' }, remote: true do %>
            <i class="icon-trash"></i>
          <% end %>
        </li>
      </ul>
    </th>
  </tr>

  <!-- Add-Task row -->
  <tr class="add-new">
    <td colspan="3">
      <%= simple_form_for([project, @task], remote: true, :html => {:class => "form-vertical form-inline task-add"}) do |f| %>
        <%= f.input :name, :label => false, :input_html => {class: "task_name", id: "task_name_p#{project.id}",  size: "125" } %>
        <%= f.submit "Add Task",:class=>"btn btn-primary" %>
      <% end %>
    </td>
  </tr>

  <!-- Tasks row -->
  <%= render partial: 'task-row', collection: project.task, as: 'task' %>

</table>

app/views/projects/_task-row.html.erb
<tr class="<%= "status-done" if task.done %>" id="<%= "#{task.project_id}-#{task.id}" %>">
  
  <!-- CheckBox "Set Done Status" -->
  <td class="set-done">
    <%= check_box 'task', 'done', :checked => task.done, class: "task-status-chekbox" %>
  </td>
  
  <!-- Task Name -->
  <td class="name">
    <p><%= task.name %></p>
  </td>

  <!-- Buttons: Up/Down  Priority, Details, Edit, Delete  -->
  <td class="control">
    <ul class="nav nav-pills">
      <li>
        <%= link_to change_priority_project_task_path(task.project_id, task, direction: "up"), class: "task-priority up", title: "Up priority",  method: :put, remote: true do %>
          <i class="icon-arrow-up"></i>
        <% end %>
        <%= link_to change_priority_project_task_path(task.project_id, task, direction: "down"), class: "task-priority down", title: "Down priority",  method: :put, remote: true do %>
          <i class="icon-arrow-down"></i>
        <% end %>
      </li>          
      <li>
        <%= link_to project_task_path(task.project_id, task), class: "task-show", title: "Task details", remote: true do %>
          <i class="icon-chevron-right"></i>
        <% end %>
      </li>
      <li>
        <%= link_to edit_project_task_path(task.project_id, task), class: "task-edit", title: "Edit task", remote: true do %>
          <i class="icon-pencil"></i>
        <% end %>
      </li>
      <li>
        <%= link_to project_task_path(task.project_id, task), class: "task-delete", title: "Remove task", method: :delete, data: { confirm: 'Are you sure?' }, remote: true do %>
          <i class="icon-trash"></i>
        <% end %>
      </li>
    </ul>
  </td>
</tr>