config/routes.rb
TaskManager::Application.routes.draw do

  root to: 'sessions#home'

  resources :projects, except: [:show] do
    resources :tasks, except: [:index, :new] do
      member do
        put 'change_priority'
      end
    end
  end

  match '/projects' => 'projects#index', via: [:delete, :put, :get]

  resources :sessions, except: [:show, :edit, :update]
  match '/logout' => 'sessions#destroy', via: :delete
  match '/login' => 'sessions#new'

  resources :users, only: [:create]

  match '*a' => 'application#rescue404'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskManager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrapper">

    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <ul class="nav pull-right">
            <li class="user_email"></li>
            <li class="login"><%= link_to "Log In", login_path, method: "delete", remote: true %></li>
            <li class="logout"><%= link_to "Log Out", logout_path, method: "delete"%></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row" id="alert-area"></div>

      <div class="row" id="title"><h1>SIMPLE TODO LISTS</h1></div>

      <div class="row" id="main"></div>

      <div class="row text-center" id="project-add-button">
        <%= link_to 'Add TODO List', new_project_path, :class=>"btn btn-primary no-visited-hightlite project-add", remote: true %>
      </div>

      <div class="row" id="modal"></div>
      
      <div class="clear"></div>
    </div>

    <div id="ajax-req-processing"><%= image_tag("AjaxLoading.gif") %></div>  
    
  </div>
</body>
</html>